### ISSUE TITLE
Add CodeCov

### ISSUE THREAD

**Issue by brunoocasali** [meilisearch/meilisearch-java#641]
⚠️ This issue is generated, it means the examples and the namings do not necessarily correspond to the language of this repository.
Also, if you are a maintainer, please add any clarification and instructions about this issue.

Sorry if this is already wholly/partially implemented. Feel free to let me know about the state of this issue in the repo.

Related to https://github.com/meilisearch/integration-guides/issues/59

----

Codecov helps us to know if a PR add non-tested code. If it's the case, we don't accept the PR. 
It's easy to install, easy to configure.

### TODO:

- [ ] Add CodeCov to this repository.
- [ ] Add the CodeCov badge on this repository README.md
- [ ] Ensure a minimum coverage is accepted (optional)

**Comment by StanislavMontag** [comment]
Hey,
Could you please assign this task to me?

**Comment by brunoocasali** [comment]
Hi @StanislavMontag 

We prefer not assigning external people to our issues.
Because people often ask to be assigned and never return, which discourages other potential contributions.
We will accept and merge the first PR that fixes correctly and implements the issue.

**Comment by tonyghouse** [comment]
hi @brunoocasali  . Raised PR for codecov config https://github.com/meilisearch/meilisearch-java/pull/644. check and suggest any changes if needed. have a doubt on the default test reports location in build.gradle. should i remove it or kept as it is?
